export const SALT_LAKE_VALLEY = [
	'salt lake city',
	'west valley city',
	'provo',
	'west jordan',
	'orem',
	'sandy',
	'ogden',
	'st. george',
	'saint george',
	'layton',
	'south jordan',
	'lehi',
	'millcreek',
	'taylorsville',
	'logan',
	'murray',
	'draper',
	'bountiful',
	'riverton',
	'roy',
	'spanish fork',
	'pleasant grove',
	'kearns',
	'cottonwood heights',
	'tooele',
	'springville',
	'midvale',
	'herriman',
	'clearfield',
	'kaysville',
	'american fork',
	'syracuse',
	'south salt lake',
	'clinton',
	'north salt lake',
	'brigham city',
	'farmington',
	'holladay',
	'bluffdale',
	'centerville'
]