export const SALT_LAKE_VALLEY = [
	'salt lake city',
	'west valley city',
	'provo',
	'west jordan',
	'orem',
	'sandy',
	'ogden',
	'st. george',
	'saint george',
	'layton',
	'south jordan',
	'lehi',
	'millcreek',
	'taylorsville',
	'logan',
	'murray',
	'draper',
	'bountiful',
	'riverton',
	'roy',
	'spanish fork',
	'pleasant grove',
	'kearns',
	'cottonwood heights',
	'tooele',
	'springville',
	'midvale',
	'herriman',
	'clearfield',
	'kaysville',
	'american fork',
	'syracuse',
	'south salt lake',
	'clinton',
	'north salt lake',
	'brigham city',
	'farmington',
	'holladay',
	'bluffdale',
	'centerville'
]

export const COUNTRIES = [
	{ label: "Australia", value: "Australia" },
	{ label: "Austria", value: "Austria" },
	{ label: "Belgium", value: "Belgium" },
	{ label: "Canada", value: "Canada" },
	{ label: "Croatia", value: "Croatia" },
	{ label: "Cyprus", value: "Cyprus" },
	{ label: "Czech Republic", value: "Czech Republic" },
	{ label: "Denmark", value: "Denmark" },
	{ label: "Estonia", value: "Estonia" },
	{ label: "Finland", value: "Finland" },
	{ label: "France", value: "France" },
	{ label: "Germany", value: "Germany" },
	{ label: "Greece", value: "Greece" },
	{ label: "Hungry", value: "Hungry" },
	{ label: "Iceland", value: "Iceland" },
	{ label: "India", value: "India" },
	{ label: "Indonesia", value: "Indonesia" },
	{ label: "Ireland", value: "Ireland" },
	{ label: "Israel", value: "Israel" },
	{ label: "Italy", value: "Italy" },
	{ label: "Japan", value: "Japan" },
	{ label: "Latvia", value: "Latvia" },
	{ label: "Lithuania", value: "Lithuania" },
	{ label: "Luxembourg", value: "Luxembourg" },
	{ label: "Malaysia", value: "Malaysia" },
	{ label: "Malta", value: "Malta" },
	{ label: "Mexico", value: "Mexico" },
	{ label: "Netherlands", value: "Netherlands" },
	{ label: "New Zealand", value: "New Zealand" },
	{ label: "Norway", value: "Norway" },
	{ label: "Poland", value: "Poland" },
	{ label: "Portugal", value: "Portugal" },
	{ label: "Romania", value: "Romania" },
	{ label: "Slovakia", value: "Slovakia" },
	{ label: "Slovenia", value: "Slovenia" },
	{ label: "Spain", value: "Spain" },
	{ label: "Sweden", value: "Sweden" },
	{ label: "Switzerland", value: "Switzerland" },
	{ label: "United Kingdom", value: "United Kingdom" },
	{ label: "United States of America", value: "United States of America" }
]
