export const SALT_LAKE_VALLEY = [
	'salt lake city',
	'west valley city',
	'provo',
	'west jordan',
	'orem',
	'sandy',
	'ogden',
	'st. george',
	'saint george',
	'layton',
	'south jordan',
	'lehi',
	'millcreek',
	'taylorsville',
	'logan',
	'murray',
	'draper',
	'bountiful',
	'riverton',
	'roy',
	'spanish fork',
	'pleasant grove',
	'kearns',
	'cottonwood heights',
	'tooele',
	'springville',
	'midvale',
	'herriman',
	'clearfield',
	'kaysville',
	'american fork',
	'syracuse',
	'south salt lake',
	'clinton',
	'north salt lake',
	'brigham city',
	'farmington',
	'holladay',
	'bluffdale',
	'centerville'
]

export const STATES = [
	{ value: 'AK', label: 'Alaska'},
	{ value: 'AL', label: 'Alabama'},
	{ value: 'AR', label: 'Arkansas'},
	{ value: 'AZ', label: 'Arizona'},
	{ value: 'CA', label: 'California'},
	{ value: 'CO', label: 'Colorado'},
	{ value: 'CT', label: 'Connecticut'},
	{ value: 'DE', label: 'Delaware'},
	{ value: 'FL', label: 'Florida'},
	{ value: 'GA', label: 'Georgia'},
	{ value: 'HI', label: 'Hawaii'},
	{ value: 'IA', label: 'Iowa'},
	{ value: 'ID', label: 'Idaho'},
	{ value: 'IL', label: 'Illinois'},
	{ value: 'IN', label: 'Indiana'},
	{ value: 'KS', label: 'Kansas'},
	{ value: 'KY', label: 'Kentucky'},
	{ value: 'LA', label: 'Louisiana'},
	{ value: 'MA', label: 'Massachusetts'},
	{ value: 'MD', label: 'Maryland'},
	{ value: 'ME', label: 'Maine'},
	{ value: 'MI', label: 'Michigan'},
	{ value: 'MN', label: 'Minnesota'},
	{ value: 'MO', label: 'Missouri'},
	{ value: 'MS', label: 'Mississippi'},
	{ value: 'MT', label: 'Montana'},
	{ value: 'NC', label: 'North Carolina'},
	{ value: 'ND', label: 'North Dakota'},
	{ value: 'NE', label: 'Nebraska'},
	{ value: 'NH', label: 'New Hampshire'},
	{ value: 'NJ', label: 'New Jersey'},
	{ value: 'NM', label: 'New Mexico'},
	{ value: 'NV', label: 'Nevada'},
	{ value: 'NY', label: 'New York'},
	{ value: 'OH', label: 'Ohio'},
	{ value: 'OK', label: 'Oklahoma'},
	{ value: 'OR', label: 'Oregon'},
	{ value: 'PA', label: 'Pennsylvania'},
	{ value: 'RI', label: 'Rhode Island'},
	{ value: 'SC', label: 'South Carolina'},
	{ value: 'SD', label: 'South Dakota'},
	{ value: 'TN', label: 'Tennessee'},
	{ value: 'TX', label: 'Texas'},
	{ value: 'UT', label: 'Utah'},
	{ value: 'VA', label: 'Virginia'},
	{ value: 'VT', label: 'Vermont'},
	{ value: 'WA', label: 'Washington'},
	{ value: 'DC', label: 'Washington, DC'},
	{ value: 'WI', label: 'Wisconsin'},
	{ value: 'WV', label: 'West Virginia'},
	{ value: 'WY', label: 'Wyoming'}
];